// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace XUnit_BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class РасчётШтрафаДляЧитателейССемейнымАбонементомFeature : object, global::Xunit.IClassFixture<РасчётШтрафаДляЧитателейССемейнымАбонементомFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("ru"), "Features", "Расчёт штрафа для читателей с семейным абонементом", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FamilyFineRule.feature"
#line hidden
        
        public РасчётШтрафаДляЧитателейССемейнымАбонементомFeature(РасчётШтрафаДляЧитателейССемейнымАбонементомFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/FamilyFineRule.feature.ndjson", 9);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Просрочка в льготный период не штрафуется")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Расчёт штрафа для читателей с семейным абонементом")]
        [global::Xunit.TraitAttribute("Description", "Просрочка в льготный период не штрафуется")]
        public async global::System.Threading.Tasks.Task ПросрочкаВЛьготныйПериодНеШтрафуется()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Просрочка в льготный период не штрафуется", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await testRunner.GivenAsync("читатель с семейным абонементом", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 6
  await testRunner.WhenAsync("книга просрочена на 3 дня", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 7
  await testRunner.ThenAsync("штраф равен 0 рублей", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="После льготного периода начисляется 2 рубля в день")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Расчёт штрафа для читателей с семейным абонементом")]
        [global::Xunit.TraitAttribute("Description", "После льготного периода начисляется 2 рубля в день")]
        public async global::System.Threading.Tasks.Task ПослеЛьготногоПериодаНачисляется2РубляВДень()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("После льготного периода начисляется 2 рубля в день", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await testRunner.GivenAsync("читатель с семейным абонементом", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 11
  await testRunner.WhenAsync("книга просрочена на 8 дней", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 12
  await testRunner.ThenAsync("штраф равен 6 рублей", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Штраф ограничен потолком в 100 рублей")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Расчёт штрафа для читателей с семейным абонементом")]
        [global::Xunit.TraitAttribute("Description", "Штраф ограничен потолком в 100 рублей")]
        public async global::System.Threading.Tasks.Task ШтрафОграниченПотолкомВ100Рублей()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Штраф ограничен потолком в 100 рублей", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await testRunner.GivenAsync("читатель с семейным абонементом", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 16
  await testRunner.WhenAsync("книга просрочена на 100 дней", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 17
  await testRunner.ThenAsync("штраф равен 100 рублей", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Расчёт штрафа для разных периодов")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Расчёт штрафа для читателей с семейным абонементом")]
        [global::Xunit.TraitAttribute("Description", "Расчёт штрафа для разных периодов")]
        [global::Xunit.InlineDataAttribute("0", "0", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("5", "0", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("6", "2", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("100", "100", "6", new string[0])]
        public async global::System.Threading.Tasks.Task РасчётШтрафаДляРазныхПериодов(string дни, string штраф, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("дни", дни);
            argumentsOfScenario.Add("штраф", штраф);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Расчёт штрафа для разных периодов", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await testRunner.GivenAsync("читатель с семейным абонементом", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 21
  await testRunner.WhenAsync(string.Format("книга просрочена на {0} дней", дни), ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 22
  await testRunner.ThenAsync(string.Format("штраф равен {0} рублей", штраф), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await РасчётШтрафаДляЧитателейССемейнымАбонементомFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await РасчётШтрафаДляЧитателейССемейнымАбонементомFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
